INSERT INTO packs (pack_id, author) VALUES (1,1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (1, 1, 'https://social-hub.ru/uploads/stickers/1.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (1, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (2, 1, 'https://social-hub.ru/uploads/stickers/2.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (2, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (3, 1, 'https://social-hub.ru/uploads/stickers/3.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (3, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (4, 1, 'https://social-hub.ru/uploads/stickers/4.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (4, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (5, 1, 'https://social-hub.ru/uploads/stickers/5.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (5, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (6, 1, 'https://social-hub.ru/uploads/stickers/6.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (6, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (7, 1, 'https://social-hub.ru/uploads/stickers/7.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (7, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (8, 1, 'https://social-hub.ru/uploads/stickers/8.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (8, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (9, 1, 'https://social-hub.ru/uploads/stickers/9.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (9, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (10, 1, 'https://social-hub.ru/uploads/stickers/10.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (10, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (11, 1, 'https://social-hub.ru/uploads/stickers/11.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (11, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (12, 1, 'https://social-hub.ru/uploads/stickers/12.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (12, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (13, 1, 'https://social-hub.ru/uploads/stickers/13.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (13, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (14, 1, 'https://social-hub.ru/uploads/stickers/14.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (14, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (15, 1, 'https://social-hub.ru/uploads/stickers/15.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (15, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (16, 1, 'https://social-hub.ru/uploads/stickers/16.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (16, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (17, 1, 'https://social-hub.ru/uploads/stickers/17.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (17, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (18, 1, 'https://social-hub.ru/uploads/stickers/18.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (18, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (19, 1, 'https://social-hub.ru/uploads/stickers/19.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (19, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (20, 1, 'https://social-hub.ru/uploads/stickers/20.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (20, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (21, 1, 'https://social-hub.ru/uploads/stickers/21.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (21, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (22, 1, 'https://social-hub.ru/uploads/stickers/22.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (22, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (23, 1, 'https://social-hub.ru/uploads/stickers/23.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (23, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (24, 1, 'https://social-hub.ru/uploads/stickers/24.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (24, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (25, 1, 'https://social-hub.ru/uploads/stickers/25.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (25, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (26, 1, 'https://social-hub.ru/uploads/stickers/26.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (26, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (27, 1, 'https://social-hub.ru/uploads/stickers/27.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (27, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (28, 1, 'https://social-hub.ru/uploads/stickers/28.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (28, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (29, 1, 'https://social-hub.ru/uploads/stickers/29.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (29, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (30, 1, 'https://social-hub.ru/uploads/stickers/30.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (30, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (31, 1, 'https://social-hub.ru/uploads/stickers/31.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (31, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (32, 1, 'https://social-hub.ru/uploads/stickers/32.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (32, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (33, 1, 'https://social-hub.ru/uploads/stickers/33.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (33, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (34, 1, 'https://social-hub.ru/uploads/stickers/34.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (34, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (35, 1, 'https://social-hub.ru/uploads/stickers/35.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (35, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (36, 1, 'https://social-hub.ru/uploads/stickers/36.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (36, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (37, 1, 'https://social-hub.ru/uploads/stickers/37.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (37, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (38, 1, 'https://social-hub.ru/uploads/stickers/38.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (38, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (39, 1, 'https://social-hub.ru/uploads/stickers/39.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (39, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (40, 1, 'https://social-hub.ru/uploads/stickers/40.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (40, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (41, 1, 'https://social-hub.ru/uploads/stickers/41.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (41, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (42, 1, 'https://social-hub.ru/uploads/stickers/42.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (42, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (43, 1, 'https://social-hub.ru/uploads/stickers/43.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (43, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (44, 1, 'https://social-hub.ru/uploads/stickers/44.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (44, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (45, 1, 'https://social-hub.ru/uploads/stickers/45.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (45, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (46, 1, 'https://social-hub.ru/uploads/stickers/46.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (46, 1);
INSERT INTO stickers(stick_id, pack_id, sticker_link) VALUES (47, 1, 'https://social-hub.ru/uploads/stickers/47.png');
INSERT INTO packstickers(stick_id, pack_id) VALUES (47, 1);
