global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'server'
    static_configs:
      - targets: ['localhost:3001']
        labels:
          group: 'main_server'

      - targets: ['localhost:3081']
        labels:
          group: 'messages_and_chats_micro'

  - job_name: 'system_status'
    static_configs:
      - targets: ['localhost:9100']


rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093