// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2a129749DecodeMainInternalModels(in *jlexer.Lexer, out *ChatAndMessages) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chatInfo":
			easyjson2a129749DecodeMainInternalModels1(in, &out.ChatInfo)
		case "chatMessages":
			if in.IsNull() {
				in.Skip()
				out.ChatMessages = nil
			} else {
				in.Delim('[')
				if out.ChatMessages == nil {
					if !in.IsDelim(']') {
						out.ChatMessages = make([]Message, 0, 1)
					} else {
						out.ChatMessages = []Message{}
					}
				} else {
					out.ChatMessages = (out.ChatMessages)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Message
					easyjson2a129749DecodeMainInternalModels2(in, &v1)
					out.ChatMessages = append(out.ChatMessages, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a129749EncodeMainInternalModels(out *jwriter.Writer, in ChatAndMessages) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chatInfo\":"
		out.RawString(prefix[1:])
		easyjson2a129749EncodeMainInternalModels1(out, in.ChatInfo)
	}
	{
		const prefix string = ",\"chatMessages\":"
		out.RawString(prefix)
		if in.ChatMessages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.ChatMessages {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson2a129749EncodeMainInternalModels2(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChatAndMessages) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a129749EncodeMainInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatAndMessages) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a129749EncodeMainInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChatAndMessages) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a129749DecodeMainInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatAndMessages) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a129749DecodeMainInternalModels(l, v)
}
func easyjson2a129749DecodeMainInternalModels2(in *jlexer.Lexer, out *Message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chatId":
			out.ChatId = string(in.String())
		case "chatPhoto":
			out.ChatPhoto = string(in.String())
		case "chatName":
			out.ChatName = string(in.String())
		case "authorName":
			out.AuthorName = string(in.String())
		case "authorSurname":
			out.AuthorSurname = string(in.String())
		case "authorUrl":
			out.AuthorUrl = string(in.String())
		case "authorPhoto":
			out.AuthorPhoto = string(in.String())
		case "text":
			out.Text = string(in.String())
		case "time":
			out.Time = string(in.String())
		case "sticker":
			out.Sticker = string(in.String())
		case "isMe":
			out.IsMe = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a129749EncodeMainInternalModels2(out *jwriter.Writer, in Message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chatId\":"
		out.RawString(prefix[1:])
		out.String(string(in.ChatId))
	}
	{
		const prefix string = ",\"chatPhoto\":"
		out.RawString(prefix)
		out.String(string(in.ChatPhoto))
	}
	{
		const prefix string = ",\"chatName\":"
		out.RawString(prefix)
		out.String(string(in.ChatName))
	}
	{
		const prefix string = ",\"authorName\":"
		out.RawString(prefix)
		out.String(string(in.AuthorName))
	}
	{
		const prefix string = ",\"authorSurname\":"
		out.RawString(prefix)
		out.String(string(in.AuthorSurname))
	}
	{
		const prefix string = ",\"authorUrl\":"
		out.RawString(prefix)
		out.String(string(in.AuthorUrl))
	}
	{
		const prefix string = ",\"authorPhoto\":"
		out.RawString(prefix)
		out.String(string(in.AuthorPhoto))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.String(string(in.Time))
	}
	if in.Sticker != "" {
		const prefix string = ",\"sticker\":"
		out.RawString(prefix)
		out.String(string(in.Sticker))
	}
	{
		const prefix string = ",\"isMe\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsMe))
	}
	out.RawByte('}')
}
func easyjson2a129749DecodeMainInternalModels1(in *jlexer.Lexer, out *ChatInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "isGroupChat":
			out.IsGroupChat = bool(in.Bool())
		case "chatId":
			out.ChatId = string(in.String())
		case "chatCounter":
			out.ChatCounter = int(in.Int())
		case "statusOnline":
			out.StatusOnline = bool(in.Bool())
		case "privateName":
			out.PrivateName = string(in.String())
		case "privateSurname":
			out.PrivateSurname = string(in.String())
		case "privateUrl":
			out.PrivateUrl = string(in.String())
		case "chatName":
			out.ChatName = string(in.String())
		case "chatPhoto":
			out.ChatPhoto = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a129749EncodeMainInternalModels1(out *jwriter.Writer, in ChatInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"isGroupChat\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsGroupChat))
	}
	{
		const prefix string = ",\"chatId\":"
		out.RawString(prefix)
		out.String(string(in.ChatId))
	}
	{
		const prefix string = ",\"chatCounter\":"
		out.RawString(prefix)
		out.Int(int(in.ChatCounter))
	}
	{
		const prefix string = ",\"statusOnline\":"
		out.RawString(prefix)
		out.Bool(bool(in.StatusOnline))
	}
	{
		const prefix string = ",\"privateName\":"
		out.RawString(prefix)
		out.String(string(in.PrivateName))
	}
	{
		const prefix string = ",\"privateSurname\":"
		out.RawString(prefix)
		out.String(string(in.PrivateSurname))
	}
	{
		const prefix string = ",\"privateUrl\":"
		out.RawString(prefix)
		out.String(string(in.PrivateUrl))
	}
	{
		const prefix string = ",\"chatName\":"
		out.RawString(prefix)
		out.String(string(in.ChatName))
	}
	{
		const prefix string = ",\"chatPhoto\":"
		out.RawString(prefix)
		out.String(string(in.ChatPhoto))
	}
	out.RawByte('}')
}
