// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9b8f5552DecodeMainInternalModels(in *jlexer.Lexer, out *Chat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "isGroupChat":
			out.IsGroupChat = bool(in.Bool())
		case "chatId":
			out.ChatId = string(in.String())
		case "chatPhoto":
			out.ChatPhoto = string(in.String())
		case "chatName":
			out.ChatName = string(in.String())
		case "privateName":
			out.PrivateName = string(in.String())
		case "privateSurname":
			out.PrivateSurname = string(in.String())
		case "privateUrl":
			out.PrivateUrl = string(in.String())
		case "statusOnline":
			out.StatusOnline = bool(in.Bool())
		case "lastMessageAuthorPhoto":
			out.LastMessageAuthorPhoto = string(in.String())
		case "lastMessageTime":
			out.LastMessageTime = string(in.String())
		case "lastMessageTxt":
			out.LastMessageTxt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9b8f5552EncodeMainInternalModels(out *jwriter.Writer, in Chat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"isGroupChat\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsGroupChat))
	}
	{
		const prefix string = ",\"chatId\":"
		out.RawString(prefix)
		out.String(string(in.ChatId))
	}
	{
		const prefix string = ",\"chatPhoto\":"
		out.RawString(prefix)
		out.String(string(in.ChatPhoto))
	}
	{
		const prefix string = ",\"chatName\":"
		out.RawString(prefix)
		out.String(string(in.ChatName))
	}
	if in.PrivateName != "" {
		const prefix string = ",\"privateName\":"
		out.RawString(prefix)
		out.String(string(in.PrivateName))
	}
	if in.PrivateSurname != "" {
		const prefix string = ",\"privateSurname\":"
		out.RawString(prefix)
		out.String(string(in.PrivateSurname))
	}
	if in.PrivateUrl != "" {
		const prefix string = ",\"privateUrl\":"
		out.RawString(prefix)
		out.String(string(in.PrivateUrl))
	}
	{
		const prefix string = ",\"statusOnline\":"
		out.RawString(prefix)
		out.Bool(bool(in.StatusOnline))
	}
	{
		const prefix string = ",\"lastMessageAuthorPhoto\":"
		out.RawString(prefix)
		out.String(string(in.LastMessageAuthorPhoto))
	}
	{
		const prefix string = ",\"lastMessageTime\":"
		out.RawString(prefix)
		out.String(string(in.LastMessageTime))
	}
	{
		const prefix string = ",\"lastMessageTxt\":"
		out.RawString(prefix)
		out.String(string(in.LastMessageTxt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Chat) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9b8f5552EncodeMainInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Chat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9b8f5552EncodeMainInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Chat) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9b8f5552DecodeMainInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Chat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9b8f5552DecodeMainInternalModels(l, v)
}
