// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson31e6d0d0DecodeMainInternalModels(in *jlexer.Lexer, out *NewChatUsers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chatPhoto":
			out.ChatPhoto = string(in.String())
		case "chatName":
			out.ChatName = string(in.String())
		case "usersLogin":
			if in.IsNull() {
				in.Skip()
				out.UsersLogin = nil
			} else {
				in.Delim('[')
				if out.UsersLogin == nil {
					if !in.IsDelim(']') {
						out.UsersLogin = make([]string, 0, 4)
					} else {
						out.UsersLogin = []string{}
					}
				} else {
					out.UsersLogin = (out.UsersLogin)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.UsersLogin = append(out.UsersLogin, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson31e6d0d0EncodeMainInternalModels(out *jwriter.Writer, in NewChatUsers) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ChatPhoto != "" {
		const prefix string = ",\"chatPhoto\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ChatPhoto))
	}
	if in.ChatName != "" {
		const prefix string = ",\"chatName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ChatName))
	}
	if len(in.UsersLogin) != 0 {
		const prefix string = ",\"usersLogin\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.UsersLogin {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NewChatUsers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson31e6d0d0EncodeMainInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NewChatUsers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson31e6d0d0EncodeMainInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NewChatUsers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson31e6d0d0DecodeMainInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NewChatUsers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson31e6d0d0DecodeMainInternalModels(l, v)
}
