// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PhotoInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PhotoInfo ) UnmarshalJSON([]byte) error { return nil }
func ( PhotoInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PhotoInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PhotoInfo *PhotoInfo
