// Code generated by MockGen. DO NOT EDIT.
// Source: main/internal/albums (interfaces: AlbumUseCase)

// Package mock_albums is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	models "main/internal/models"
	reflect "reflect"
)

// MockAlbumUseCase is a mock of AlbumUseCase interface
type MockAlbumUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAlbumUseCaseMockRecorder
}

// MockAlbumUseCaseMockRecorder is the mock recorder for MockAlbumUseCase
type MockAlbumUseCaseMockRecorder struct {
	mock *MockAlbumUseCase
}

// NewMockAlbumUseCase creates a new mock instance
func NewMockAlbumUseCase(ctrl *gomock.Controller) *MockAlbumUseCase {
	mock := &MockAlbumUseCase{ctrl: ctrl}
	mock.recorder = &MockAlbumUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAlbumUseCase) EXPECT() *MockAlbumUseCaseMockRecorder {
	return m.recorder
}

// CreateAlbum mocks base method
func (m *MockAlbumUseCase) CreateAlbum(arg0 int, arg1 models.AlbumReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlbum", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAlbum indicates an expected call of CreateAlbum
func (mr *MockAlbumUseCaseMockRecorder) CreateAlbum(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlbum", reflect.TypeOf((*MockAlbumUseCase)(nil).CreateAlbum), arg0, arg1)
}

// GetAlbums mocks base method
func (m *MockAlbumUseCase) GetAlbums(arg0 int) ([]models.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbums", arg0)
	ret0, _ := ret[0].([]models.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlbums indicates an expected call of GetAlbums
func (mr *MockAlbumUseCaseMockRecorder) GetAlbums(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbums", reflect.TypeOf((*MockAlbumUseCase)(nil).GetAlbums), arg0)
}
