// Code generated by MockGen. DO NOT EDIT.
// Source: main/internal/photos (interfaces: PhotoRepository)

// Package mock_photos is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	models "main/internal/models"
	reflect "reflect"
)

// MockPhotoRepository is a mock of PhotoRepository interface
type MockPhotoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPhotoRepositoryMockRecorder
}

// MockPhotoRepositoryMockRecorder is the mock recorder for MockPhotoRepository
type MockPhotoRepositoryMockRecorder struct {
	mock *MockPhotoRepository
}

// NewMockPhotoRepository creates a new mock instance
func NewMockPhotoRepository(ctrl *gomock.Controller) *MockPhotoRepository {
	mock := &MockPhotoRepository{ctrl: ctrl}
	mock.recorder = &MockPhotoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPhotoRepository) EXPECT() *MockPhotoRepositoryMockRecorder {
	return m.recorder
}

// GetPhotosFromAlbum mocks base method
func (m *MockPhotoRepository) GetPhotosFromAlbum(arg0 int) (models.Photos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhotosFromAlbum", arg0)
	ret0, _ := ret[0].(models.Photos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPhotosFromAlbum indicates an expected call of GetPhotosFromAlbum
func (mr *MockPhotoRepositoryMockRecorder) GetPhotosFromAlbum(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhotosFromAlbum", reflect.TypeOf((*MockPhotoRepository)(nil).GetPhotosFromAlbum), arg0)
}

// UploadPhotoToAlbum mocks base method
func (m *MockPhotoRepository) UploadPhotoToAlbum(arg0 models.PhotoInAlbum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPhotoToAlbum", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadPhotoToAlbum indicates an expected call of UploadPhotoToAlbum
func (mr *MockPhotoRepositoryMockRecorder) UploadPhotoToAlbum(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhotoToAlbum", reflect.TypeOf((*MockPhotoRepository)(nil).UploadPhotoToAlbum), arg0)
}
