// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_like is a generated GoMock package.
package usecase

import (
	"github.com/golang/mock/gomock"
	"testing"
)


func Test_PhotoLike(t *testing.T) {

	var likePhoto int

	ctrl := gomock.NewController(t)
	defer ctrl.Finish()
	lRepoMock := NewMockRepositoryLike(ctrl)
	cRepoMock := NewMockCookieRepository(ctrl)
	lRepoMock.EXPECT().LikePhoto(1,1).Return(nil)
	cRepoMock.EXPECT().GetUserIdByCookie("123").Return(1,nil)
	likeUseCase := NewLikeUseRealisation(lRepoMock,cRepoMock)

	likeUseCase.LikePhoto(1,"123")

}