name: Go

on:
  push:
    branches: [ fe/rk_4_tests_usecase_66 , develop ]
  pull_request:
    branches: [ fe/rk_4_tests_usecase_66 , develop ]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.0.3
      with:
        go-version: ^1.13
    - name: Checkout code
      uses: actions/checkout@v2
    - name: ls output
      run: ls -a   
    - name: Cd into internal
      run: cd internal/ 
    - name: ls output
      run: ls -a     
    - name: Test
      run: go test -coverpkg=./... -coverprofile=cover ./...
    - name: Getting cover profile
      run: cat cover | fgrep -v "mock" | fgrep -v "pb.go" | fgrep -v "easyjson" > cover2
    - name: Getting coverage %  
      run: go tool cover -func=cover2

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:

#     - name: Set up Go 1.x
#       uses: actions/setup-go@v2.0.3
#       with:
#         go-version: ^1.13
#       id: go

#     - name: Check out code into the Go module directory
#       uses: actions/checkout@v2

#     - name: Get dependencies
#       run: |
#         go get -v -t -d ./...
#         if [ -f Gopkg.toml ]; then
#             curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#             dep ensure
#         fi

#     - name: Build
#       run: go build -v .

#     - name: Test
#       run: go test -v .
